server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: leetcode-search

  datasource:
    url: jdbc:mysql://192.168.56.10:3306/my_project
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:/mapper/*.xml

